import os

__all__ = [
    "DB_LOCATION",
    "UPDATE_FREQUENCY_SECONDS",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_DESCRIPTION_LENGTH_TG",
    "MAX_MESSAGE_LENGTH_TELEGRAM",
    "GAME_JOINER",
]

DB_LOCATION = os.path.join(__file__, "..", "data", "bot_db.sqlite")
# UPDATE_FREQUENCY_SECONDS = 6 * 60 * 60
UPDATE_FREQUENCY_SECONDS = 10
MAX_DESCRIPTION_LENGTH = 10_000
PERCENTAGE_CHANGE_TO_TRIGGER = 0.1
MAX_DESCRIPTION_LENGTH_TG = 500
MAX_MESSAGE_LENGTH_TELEGRAM = 4096
GAME_JOINER = "\n-----------------------------------------------\n"
