import os

__all__ = [
    "DB_LOCATION",
    "UPDATE_FREQUENCY_SECONDS",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_DESCRIPTION_LENGTH_TG",
    "MAX_MESSAGE_LENGTH_TELEGRAM",
    "GAME_JOINER",
    "USER_LANGUAGE_KEY",
    "MAIN_MENU_COMMAND",
    "GAME_RULE_DOMAIN_KEY",
    "MAX_LAST_MESSAGE_LENGTH",
    "SALT", "RULE_ID_LENGTH",
    "InvalidDomainError",
    "DEFAULT_DAYS_IN_FUTURE",
]

DB_LOCATION = os.path.join(__file__, "..", "data", "bot_db.sqlite")
# UPDATE_FREQUENCY_SECONDS = 6 * 60 * 60
UPDATE_FREQUENCY_SECONDS = 1
MAX_DESCRIPTION_LENGTH = 10_000
MAX_LAST_MESSAGE_LENGTH = 100
PERCENTAGE_CHANGE_TO_TRIGGER = 0.1
MAX_DESCRIPTION_LENGTH_TG = 100
MAX_MESSAGE_LENGTH_TELEGRAM = 4096
GAME_JOINER = "\n-----------------------------------------------\n"
USER_LANGUAGE_KEY = "__user_language"
MAIN_MENU_COMMAND = "menu"
GAME_RULE_DOMAIN_KEY = "game_rule_domain"
SALT = "42663"
RULE_ID_LENGTH = 10
DEFAULT_DAYS_IN_FUTURE = 14


class InvalidDomainError(ValueError):
    pass
